os: linux
dist: trusty
language: android
node_js:
  - "node"
before_install:
  - chmod +x android/gradlew
  - nvm install --lts
  - npm install -g @ionic/cli@latest
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  global:
    - CXX=g++-4.9
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
    - ANDROID_ABI=armeabi-v7a  
android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
install:
  - npm install
script:
  - ionic build
  - npx cap sync android
  - cd android
  - ./gradlew assembleDebug
