os: linux
dist: trusty
language: node_js
node_js:
  - "node"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - openjdk-8-jdk
    - lib32stdc++6
    - lib32z1
env:
  global:
    - CXX=g++-4.9
    - GRADLE_OPTS="-Xms128m"
before_install:
  - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - export PATH=$PATH:$JAVA_HOME/bin
  - unzip sdk-tools-linux-4333796.zip -d AndroidSdk
  - cd AndroidSdk/tools/bin
  - export ANDROID_HOME=~/AndroidSdk
  - export PATH=$PATH:$ANDROID_HOME/tools
  - export PATH=$PATH:$ANDROID_HOME/platform-tools
  - export ANDROID_SDK_ROOT=$ANDROID_HOME
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - yes | ./sdkmanager --sdk_root=${ANDROID_HOME} "tools"
  - ./sdkmanager --update
  - sudo apt install gradle
  - cd ~/build/wbgs-ye/ViprusWiFiv2
  - chmod +x android/gradlew
  - npm install -g @ionic/cli@latest
install:
  - yes | sdkmanager --licenses
  - npm install
script:
  - ionic build
  - npx cap sync android
  - cd android
  - ./gradlew clean assembleDebug
