os: linux
dist: trusty
language: android
node_js:
  - "node"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  global:
    - CXX=g++-4.9
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.3

    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - yes | sdkmanager "platforms;android-30"
  - chmod +x android/gradlew
  - nvm install --lts
  - npm install -g @ionic/cli@latest
install:
  - npm install
script:
  - ionic build
  - npx cap sync android
  - cd android
  - echo "org.gradle.jvmargs=-Xmx2048m -Xms512m -XX:MaxPermSize=768m" >> gradle.properties
  - ./gradlew clean assembleDebug
