
os: linux
dist: trusty
language: node_js
node_js:
  - "node"
before_install:
  - chmod +x android/gradlew
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.9
  
android:
  components:
    - build-tools-26.0.2
    - android-26
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
script:
  - npm install -g @ionic/cli@latest
  - npm install
  - ionic build
  - npx cap sync android
  - cd android
  - ./gradlew assembleDebug
