os: linux
dist: focal
language: android
addons:
  apt:
    packages:
    - g++-4.9
    - openjdk-8-jdk-headless
    - lib32stdc++6
    - lib32z1
env:
  global:
    - CXX=g++-4.9
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.3

    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  - export PATH=$PATH:$JAVA_HOME/bin
  - unzip sdk-tools-linux-4333796.zip -d Android
  - cd Android/tools/bin
  - yes | ./sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
  - export ANDROID_HOME=/home/<user>/Android
  - export PATH=$PATH:$ANDROID_HOME/tools
  - export PATH=$PATH:$ANDROID_HOME/platform-tools
  - export ANDROID_SDK_ROOT=$ANDROID_HOME
  - sdkmanager --sdk_root=${ANDROID_HOME} "tools"
  - sdkmanager --update
  - sdkmanager --list
  - sdkmanager "build-tools;30.0.3" "platform-tools" "platforms;android-30" "tools"
  - yes | sdkmanager --licenses
  - apt install gradle
  - chmod +x android/gradlew
  - nvm install --lts
  - npm install -g @ionic/cli@latest
install:
  - npm install
script:
  - ionic build
  - npx cap sync android
  - cd android
  - echo "org.gradle.jvmargs=-Xmx768m -Xms256m -XX:MaxPermSize=768m" >> gradle.properties
  - ./gradlew clean
  - ./gradlew clean assembleDebug
